### ISSUE TITLE
1.16 snapshot crash

### ISSUE THREAD

**Issue by end-user** [flier268/AutoHarvestMod#3]
Tried [1.16]AutoHarvest-1.0.4.jar, game crashed when trying to change the harvest mode (h key):

```
java.lang.NoSuchMethodError: net/minecraft/class_2588.<init>(Ljava/lang/String;)V (loaded from file:/C:/lib/MultiMC/instances/20w15a/.minecraft/.fabric/remappedJars/minecraft-1.16-alpha.20.16.a/intermediary-minecraft-20w16a-client.jar by net.fabricmc.loader.launch.knot.KnotClassLoader@5a65390a) called from class com.flier268.autoharvest.AutoHarvest (loaded from file:/C:/lib/MultiMC/instances/20w15a/.minecraft/mods/%5B1.16%5DAutoHarvest-1.0.4.jar by net.fabricmc.loader.launch.knot.KnotClassLoader@5a65390a).
	at com.flier268.autoharvest.AutoHarvest.msg(AutoHarvest.java:65)
	at com.flier268.autoharvest.KeyPressListener.onProcessKey(KeyPressListener.java:53)
	at com.flier268.autoharvest.KeyPressListener.lambda$new$0(KeyPressListener.java:42)
	at com.flier268.autoharvest.KeyPressListener$$Lambda$1588/0000000000000000.tick(Unknown Source)
	at net.minecraft.class_310.handler$zdc000$tick(class_310.java:4123)
...
```

Snapshot 20w16a, fabric: Fabric API 0.5.11+build.322-1.16, fabricloader: Fabric Loader 0.8.2+build.194

**Comment by flier268** [comment]
is the 1.0.5 fix it?

**Comment by end-user** [comment]
Actually 1.0.4 began working with the actual release of 1.16; not sure why.  I will pull 1.0.5 and test it.
